export const UPDATE_POKEMONS = "UPDATE_POKEMONS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_POKETYPES = "UPDATE_POKETYPES";
export const UPDATE_CURRENT_POKETYPE = "UPDATE_CURRENT_POKETYPE";
